### ISSUE TITLE
Does Noke name matter?

### ISSUE THREAD

**Issue by terence-codigo** [noke-inc/noke-mobile-library-android#19]
https://github.com/noke-inc/noke-mobile-library-android/blob/a9f0aba095127bd100677b2c0e95d759e1310560/app/src/main/java/com/noke/nokeapidemo/MainActivity.java#L107

With reference to the above line in the sample app, does `name` matter when I `addNokeDevice`? 

I'm currently retrieving the `name` and `mac` from the Noke API call and doing:

```
NokeDevice noke1 = new NokeDevice(name, mac);
mNokeService.addNokeDevice(noke1);
```

I am facing an issue where I am able to scan and detect everything except one particular lock even though `name` and `mac` are verified to be correct.

**Comment by sapsley** [comment]
Name is only used for UI purposes and does not affect scanning or detection of the lock. Here are some troubleshooting steps to take if your phone is not detecting the lock:
- Restart the phone
- Toggle Bluetooth off and on
- Make sure lights are appearing on the lock when activated (If they're not you may need to replace the battery in the lock)
- Try using a different device to detect the lock to isolate the issue

**Comment by terence-codigo** [comment]
Thanks. It turned out to be an error in my code.

However, I think that the sample code should be updated to match the documentation to avoid confusion.
