### ISSUE TITLE
How I can check noke auto disconnect when I let it wait too long

### ISSUE THREAD

**Issue by linrium** [noke-inc/noke-mobile-library-android#3]
How I can distinguish between a device (noke) auto disconnect when I let it wait too long and when I close it by myself. It emits the same event (disconnect event). Thank you.

**Comment by khanhduytran** [comment]
Same with your ideal. I want to know how can i distinguish between those state too.

**Comment by sapsley** [comment]
Version 0.5.0 contains a new callback method: ```onNokeShutdown(NokeDevice noke, Boolean isLocked, Boolean didTimeout)```

This is called when the lock goes to sleep.  
*  **```isLocked```** indicates if the lock was unlocked (```isLocked == false```)  or locked (```isLocked == true```)
*  **```didTimeout```** indicates if the lock timed out (```didTimeout == true```) or was closed manually (```didTimeout == false```)
